Run Information
========================
cognizant.intelligent.test.scripter.engine : 1.1
java.runtime.name    : Java(TM) SE Runtime Environment
java.version         : 1.8.0_141
java.home            : C:\Program Files\Java\jre1.8.0_141
os.name              : Windows 10
os.arch              : amd64
os.version           : 10.0
file.encoding        : UTF-8
========================
Run Started on Thu Apr 26 12:19:30 BST 2018
Loading Browser Profile
Loading RunManager
[Scenario:Login] [TestCase: VerifyLogin] [Description: Test Run] [Browser: Chrome] [BrowserVersion: default] [Platform: ANY][ExistingBrowser: false]
Initializing Report
[main] WARN com.cognizant.cognizantits.engine.core.TMIntegration - TM integration disabled for testcases running via design mode
ApiLink not available!!
Shutting Down Thread as there is no need for SelectiveThreading
Running Iteration 1
Launching Chrome
Launching Local Driver
Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on port 19642
Only local connections are allowed.
2018-04-26 12:19:34:04S +0100 [INFO] org.openqa.selenium.remote.ProtocolHandshake createSession:Detected dialect: OSS
Chrome Launched
Step:1   | Object: Browser | Action: Open | Input: @http://newtours.demoaut.com/mercurysignon.php | Conditon:  | @26-Apr-2018 12:19:34.034
[DONE]   | Opened Url: http://newtours.demoaut.com/mercurysignon.php

===================================================================================================

Step:1   | Object: userName | Action: Set | Input: TestData0:userName | Conditon:  | @26-Apr-2018 12:19:36.036
[DEBUG]   | Test Data Not Found, Iteration - 1 is missing. 
[Env : Default | Sheet : TestData0 | Field : userName | TestCase : Login/VerifyLogin | Reusabe : Login/Login_ReUse ]

===================================================================================================

2018-04-26 12:19:36:04S +0100 [SEVERE] com.cognizant.cognizantits.engine.core.Task onError:Error in testcase [//Login/Login_ReUse]
com.cognizant.cognizantits.engine.execution.exception.TestFailedException: Error in testcase [//Login/Login_ReUse]
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.onDataNotFoundException(TestCaseRunner.java:306)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:350)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:387)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeTestCase(TestStepRunner.java:137)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.execute(TestStepRunner.java:118)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.run(TestStepRunner.java:63)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.runStep(TestCaseRunner.java:395)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:346)
	at com.cognizant.cognizantits.engine.core.Task.runIteration(Task.java:123)
	at com.cognizant.cognizantits.engine.core.Task.run(Task.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: Test Data Not Found, Iteration - 1 is missing. 
[Env : Default | Sheet : TestData0 | Field : userName | TestCase : Login/VerifyLogin | Reusabe : Login/Login_ReUse ]
	at com.cognizant.cognizantits.engine.execution.data.DataAccessInternal.throwErrorWithCause(DataAccessInternal.java:287)
	at com.cognizant.cognizantits.engine.execution.data.DataAccess.getData(DataAccess.java:71)
	at com.cognizant.cognizantits.engine.execution.data.DataProcessor.resolve(DataProcessor.java:64)
	at com.cognizant.cognizantits.engine.core.CommandControl.sync(CommandControl.java:169)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:160)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:147)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.run(TestStepRunner.java:66)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.runStep(TestCaseRunner.java:395)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:346)
	... 11 more

[DEBUG]   | Error in testcase [//Login/Login_ReUse]

===================================================================================================


---------------------------------------------------
Testcase Name        : Login:VerifyLogin
Executed Steps       : 3
Passed Steps         : 1
Failed Steps         : 2
Time Taken           : 00:00:07
-----------------------------------------------------

Run Finished on Thu Apr 26 12:19:37 BST 2018
-----------------------------------------------------
ExecutionDate        : 26-Apr-2018 12-19-29
Executed TestCases   : 1
Passed TestCases     : 0
Failed TestCases     : 1
Time Taken           : 00:00:07
ReportPath           : file:///D:\cognizant-intelligent-test-scripter-1.1\Projects\DemoCITS\Results\TestDesign\Login\VerifyLogin\26-Apr-2018 12-19-29\summary.html
-----------------------------------------------------
[main] INFO com.cognizant.cognizantits.engine.support.DesktopApi - Trying to Open - D:\cognizant-intelligent-test-scripter-1.1\Projects\DemoCITS\Results\TestDesign\Login\VerifyLogin\26-Apr-2018 12-19-29\summary.html
[main] INFO com.cognizant.cognizantits.engine.support.DesktopApi - Trying to exec: [explorer] [%s] [D:\cognizant-intelligent-test-scripter-1.1\Projects\DemoCITS\Results\TestDesign\Login\VerifyLogin\26-Apr-2018 12-19-29\summary.html]
